# ===== APP =====
spring.application.name=portfolio-tracker

# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=paul123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== FLYWAY =====
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.docker.compose.enabled=false

jwt.secret=qhahtZxjEzGBjJMpg/e9B+qSTk1JaI/1pF5A7lLK0Ks=
jwt.expiration=86400000

asset.price.update.enabled=true
asset.price.update.interval=3600000

asset.price.alpha-vantage.api-key=L731D9JE1R0AQFCZ
asset.price.alpha-vantage.base-url=https://www.alphavantage.co/query

asset.price.coingecko.base-url=https://api.coingecko.com/api/v3
asset.price.coingecko.api-key=CG-ZRRMEoyz45oA8Cxt5BRAWg5t